### ISSUE TITLE
Settings in Tampermonkey (Chrome)

### ISSUE THREAD

**Issue by mz83** [Juici/KissCleaner#10]
Quick question, but is the settings page an upcoming feature, because it doesn't show up in the Chrome version? 
They're accessible through the code editor, but that's probably not the way you intended.

**Comment by Juici** [comment]
@mz83 you should be able to access the settings menu by pressing the HOME key or by using the userscript extension menu (eg. greasemonkey or tampermonkey menu)

**Comment by Juici** [comment]
does that work for you?
