### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by BDubbB** [Juici/KissCleaner#2]
Fullscreen appears to be broken for me. When I click the fullscreen button within the player, a black background fills the screen with the video remaining about the same size as before fullscreen.

Here is an image of it:

![kiss cleaner fullscreen](https://cloud.githubusercontent.com/assets/10868982/21806970/390d273c-d6f1-11e6-8901-6ddb4f24580e.jpg)

I'm running the script in TamperMonkey on Chrome with both the Adblock and Adblock Plus extensions installed. I do know that it is inadvisable to run both, but I just can't get a single one to block all of the ads that I want blocked. I'm also running the Anti-Adblock Killer script by Reek in TamperMonkey.

**Comment by Juici** [comment]
Would you mind telling me what settings in KissCleaner you have enabled?
Also does this bug still occur with other extensions and scripts disabled?
Do you have a userstyle running that is perhaps conflicting with the script?

I haven't been able to reproduce the same bug on kissasian on firefox. I shall try on chrome now.

**Comment by Juici** [comment]
@BDubbB should be fixed now, you just need to force an update for the userscript
