### ISSUE TITLE
Video Playback Speed Broken

### ISSUE THREAD

**Issue by Ryuza** [Juici/KissCleaner#4]
The video playback speed commands were working just fine yesterday, but not today. I am using the HTML5 player. I tried
-Restarting Firefox
-Restarting my computer
-Disabling all other scripts
-Uninstalling and reinstalling the script
-Trying it on an episode I know it worked on (Zeta Gundam ep. 36)
-Changing the hotkeys on lines 600 and 601

**Comment by Juici** [comment]
Yeah I noticed the issue myself. I'm looking at doing a cleanup and rewrite anyway.

**Comment by Ryuza** [comment]
Thanks for looking into it.
