### ISSUE TITLE
the quality

### ISSUE THREAD

**Issue by remymin0012** [Juici/KissCleaner#5]
![capture](https://cloud.githubusercontent.com/assets/26514710/24077907/fbd1b194-0c97-11e7-85cb-2c59183be36a.PNG)

the picture say it all (i don't know how to explain it, sorry)

**Comment by Juici** [comment]
Could you try to explain in more detail the issue is? From the picture everything looks normal, unless I'm missing something obvious

**Comment by Juici** [comment]
@remymin0012

Could you try to explain in more detail the issue is? From the picture everything looks normal, unless I'm missing something obvious.

Is the quality perhaps not being set to the correct value?

**Comment by remymin0012** [comment]
![capture](https://cloud.githubusercontent.com/assets/26514710/24081905/6809746e-0cf7-11e7-9068-a96082c494a9.PNG)

the 480p box appear below the video, 
when i disable the userscript it appear next to the episode list. (hope you can understand)

**Comment by Juici** [comment]
@remymin0012 that's a feature not a bug, if you don't like the positioning try disabling "resize video" in settings
